### ISSUE TITLE
Can't anyone post to your domain?

### ISSUE THREAD

**Issue by intotecho** [fabito/letsencrypt-appengine#1]
Fabito, 

I used this and it worked great. Thanks.

I had to modify app.yaml slightly to allow non-secure HTTP route and added a dot before the *.
- url: /.well-known/.*
  script: main.app

But can't anyone post a challenge response and fool letsencrypt that they own this domain?

Should the POST route be separated from the GET route and protected by admin?
- url: /post-well-known-key/.*
  script: main.app
  login: admin

Regards, Chris

**Comment by fabito** [comment]
Makes sense! Do you have a PR for that ?

**Comment by intotecho** [comment]
I ended up just writing my keys to the ACME data store and not using the POST.  After all - that proves you are admin.:)
